networks:
  ljdp:
    driver: bridge
    name: ljdp

services:
  app:
    build: .
    container_name: ljdp-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      COOKIE_PASSWORD: ${COOKIE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
    image: ghcr.io/augustinpasq/ljdp-app:1.5.2
    networks:
      - ljdp
    volumes:
      - ljdp-app:/app/public

  db:
    build: ./database
    container_name: ljdp-db
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    image: ghcr.io/augustinpasq/ljdp-db:1.5.2
    networks:
      - ljdp
    volumes:
      - ljdp-db:/var/lib/mysql

volumes:
  ljdp-app:
    name: ljdp-app
  ljdp-db:
    name: ljdp-db
